apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop_asses
  labels:
    app: djna
spec:
  replicas: 3 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: djna
  template:
    metadata:
      labels:
        app: djna
    spec:
      containers:
      - name: your-container-name
        image: your-docker-image:latest  # Replace with your Docker Hub image name
        ports:
        - containerPort: 8080  # Adjust the container port if needed
