apiVersion: apps/v1
kind: Deployment
metadata:
  name: django_assesment
  labels:
    app: djnago
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: djnago
  template:
    metadata:
      labels:
        app: djnago
    spec:
      containers:
      - name: django_asses
        image: your-docker-image:latest  # Replace with your Docker Hub image name
        ports:
        - containerPort: 8080  # Adjust the container port if needed
