apiVersion: v1
kind: Service
metadata:
  name: shop_assesment-service
  labels:
    app: shop_asses 
spec:
  selector:
    app: shop_asses 

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer